### ISSUE TITLE
Problem migrating when using sqlite

### ISSUE THREAD

**Issue by calvincanas** [khsing/laravel-world#16]
Hello,

Trying to use sqlite as database in testing caused error when it tries to migrate. 
Error was: **General error: 1 index uniq_locale already exists**

The problem might be using same index name even for different tables. 

[Reference](https://stackoverflow.com/questions/27238178/duplicate-index-on-sqlite-not-on-mysql)

**Comment by subhakumariB** [comment]
am getting this error
Execute migrate first, migrating...

In Connection.php line 664:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations)


In Connector.php line 67:

  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

**Comment by khsing** [comment]
@calvincanas @subhakumariB would you guys provide more information? like PHP version, laravel version
