### ISSUE TITLE
Can not `php artisan  world:init'

### ISSUE THREAD

**Issue by jamesriady** [khsing/laravel-world#3]
I have followed the step, but it occurs an error when I did `php artisan world:init`.
I got this error `Duplicate table: 7 ERROR: relation unique_locale has already exist`
I don't know why and I have checked all my table and I does not have the unique_locale

**Comment by wildan-m** [comment]
I've got this error

`Migration table not found.
Migration table created successfully.


  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `world_cities` add index `uniq_ci
  ty`(`country_id`, `division_id`, `name`))



  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

**Comment by khsing** [comment]
Might hit migration bugs, `string` can't be 256 long. I will take a look.

**Comment by nbyloff** [comment]
I am getting this error as well: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

The default answer of adding `Schema::defaultStringLength(191);` to your AppServiceProvider doesn't work

**Comment by kotakorange** [comment]
I have this error when do world:init 
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF  
  0\x9F\x87\xB2\xF0\x9F...' for column 'emoji' at row 3

**Comment by Deparagon** [comment]
PDOException::("SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x8         7\xA8\xF0\x9F...' for column 'emoji' at row 1")
Same error message ...
I temporarily changed the column datatype to blob in the world_countries table... so that the seed can complete...

**Comment by khsing** [comment]
Hi @Deparagon @kotakorange,  you have to use utf8mb4 for your database charset, otherwise you can't using emoji.

**Comment by khsing** [comment]
@wildanmuhlis2 you can add following lines in `app/Providers/AppServiceProvider.php` to avoid this error.

```php
use Illuminate\Support\Facades\Schema;
...
    public function boot()
    {
        Schema::defaultStringLength(191);
    }
...
```

**Comment by stephenlake** [comment]
Why was this issue was closed? Users hijacked the issue with unrelated issues to the original poster and the issue is still present for postgres users.

There's a syntax issue in 3 migration files. A duplicate index name is generated for multiple columns:

CreateWorldContinentsLocaleTable.php:
`$table->unique(['continent_id','locale'], 'uniq_locale');`

CreateWorldCountriesLocaleTable:
`$table->unique(['country_id','locale'], 'uniq_locale');`

CreateWorldDivisionsTable.php:
`$table->unique(['country_id','name'], 'uniq_division');`

You're giving multiple indexes the same name which breaks when using postgres.
**Index reference**: https://laravel.com/docs/5.7/migrations#indexes

Again, I don't understand why this issue was closed when the following was never attended to:
> I have followed the step, but it occurs an error when I did php artisan world:init.
> I got this error Duplicate table: 7 ERROR: relation unique_locale has already exist
> I don't know why and I have checked all my table and I does not have the unique_locale
